{% set version = "0.2.0" %}

package:
    name: pyopcode
    version: {{ version }}

source:
    fn: {{ version }}.tar.gz
    url: https://github.com/ClinicalGraphics/pyopcode/archive/{{ version }}.tar.gz
    md5: 34a691638136e88abd7f38ae58f24be8

build:
    number: 0
    skip: True  # [osx or win32 or linux32]
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - cmake
        - boost 1.61.*
        - pyyaml
    run:
        - python
        - numpy x.x
        - boost 1.61.*

test:
    commands:
        - py.test --pyargs pyopcode
    imports:
        - pyopcode
    requires:
        - pytest

about:
    home: https://github.com/ClinicalGraphics/pyopcode
    license: LGPL-3.0
    summary: OPCODE collision detection wrapped library with numpy bindings

extra:
    recipe-maintainers:
        - ivoflipse
        - Korijn
        - Maxyme
        - EelcoHoogendoorn
