{% set version = "0.3.4" %}

package:
  name: pyopcode
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/ClinicalGraphics/pyopcode/archive/{{ version }}.tar.gz
  md5: 5a147d1dfee1d8fac0cd0dbdc2cfda79
  
build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  skip: true  # [osx or win32 or linux32]

requirements:
  build:
  - python
  - numpy x.x
  - cmake
  - boost 1.63.*
  - setuptools
  - pyyaml
  run:
  - python
  - numpy x.x
  - boost 1.63.*

test:
  commands:
    - py.test --pyargs pyopcode
  imports:
    - pyopcode
  requires:
    - pytest
  
about:
  home: https://github.com/ClinicalGraphics/pyopcode
  license: LGPL-3.0
  summary: OPCODE collision detection wrapped library with numpy bindings (mesh-mesh and mesh-ray)
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
