{% set version = "0.3.5" %}

package:
  name: pyopcode
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/ClinicalGraphics/pyopcode/archive/{{ version }}.tar.gz
  md5: 63bd05932cebedab2a6103b6dd395152
  
build:
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  number: 0
  script: python setup.py build_ext -if && python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [osx or win32 or linux32]

requirements:
  build:
  - python
  - numpy 1.11.*
  - boost 1.67.*
  - setuptools
  run:
  - python
  - numpy >=1.11
  - boost 1.67.*

test:
  imports:
    - pyopcode

about:
  home: https://github.com/ClinicalGraphics/pyopcode
  license: LGPL-3.0
  summary: OPCODE collision detection wrapped library with numpy bindings (mesh-mesh and mesh-ray)
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
    - EelcoHoogendoorn
