{% set name = "pyopcode" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93854cabb60aefbcc14b207a2db926835cc33ee993472b7e838afd86e45a7f02
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6.0
    - pip
    - pybind11 >=2.6.0
  run:
    - python >=3.6.0
    - numpy >=1.15.0

test:
  requires:
    - pytest
  imports:
    - pyopcode
  source_files:
    - tests
  commands:
    - python -m pytest tests

about:
  summary: python bindings for opcode using pybind11.
