{% set version = "0.4.0" %}

package:
  name: pyopcode
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/ClinicalGraphics/pyopcode/archive/v{{ version }}.tar.gz
  md5: 8974d6f497a7c3e909c2cdaf7cfd3db9

build:
  features:
    - vc9 # [win and py27]
    - vc10 # [win and py34]
    - vc14 # [win and py35]
  number: 0
  skip: true  # [osx or win32 or linux32]

requirements:
  host:
    - python
    - numpy x.x
    - cmake
    - boost 1.63.*
    - setuptools
    - pyyaml
  run:
    - python
    - numpy x.x
    - boost 1.63.*

test:
  commands:
    - py.test --pyargs pyopcode
  imports:
    - pyopcode
  requires:
    - pytest

about:
  home: https://github.com/ClinicalGraphics/pyopcode
  license: LGPL-3.0
  summary: OPCODE collision detection wrapped library with numpy bindings (mesh-mesh and mesh-ray)

extra:
  recipe-maintainers:
    - Maxyme
    - EelcoHoogendoorn
