travis:
  secure:
    BINSTAR_TOKEN: uvxmyuHLbIvlTpYGOk6UEHWhR/vZm8CzQdzk7bpHyzH/XgSrnyQb2f/d0A158usbw1LLI8jLlMOFKv3Od+KoVWqyqLpEeKKb0mSJ+0wpBlyyVoZTL9MBFlbk1/9S4ddU8UlvofzVILgDF77W7io7fOjaTAG8OfGLP1GGq6X1xX2LhMMphyOBYg9s3uNW7oihTFteHBc6oVL4LLu0OeHeZKqkQfPCfUG2IBng5vibSMcQKOA82xYVXJzi073v7WK4+y+XeWLcN5mngLg+RMnLrRxfW6/gqv4pvYKzzVKXugWVs3sF5cECNzCiaoPsqKVjKbzRiGqGaLOR08tbNojv8VlwXWry+leyAXPgCXhI4cxu8s4qnwCG9YWCQ+1cb1BH8M0G9H3HA2gZkil7iYCbbHLaVe7Q8dqwmJA2bbpUlf6JrYcDGDwRb5LF9UdKqMeYA/2reQP1Tpl/f3Axb0L09LpxMOjurNYmhWS3Zd4o1KIXhv9mi++L2FK9yr7cip9JgTJptwNJ6xwabyqJqacjJ8O9y/WOMoSVB+PFfik4cK1roqsC+VvUrHzVIkd0AI1Kd4BcMz0QM9YtffQsl2TAUO5wZL3FkHTsLH2A2yV0jA2Cfsx4wgPUBMqFAK2OJjUzHhVMZtukO9udIUicwER1Z2vxnvQVW6vUWBUFyWNWcdk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
