travis:
  secure:
    BINSTAR_TOKEN: pqziTArtRFd8LmXOkpN9tdtQPHtkJ7BdBFxS/P+qPEsJMW+WZhR1cINSANHsvOLP5JgJ1kQdxbEv//AexTz61a98UBxi4W5mwtZb9Hb/Swh+CxR9oU9SdeY3xW3W2QIrR9EiS1hzv3hwY2wnsdiTkovmlt7GGMK95ph9yAG8N4OJiQhbJrDwaA757Fhlx1htptawonB8b1Dnb/PWiZ/c1fQAm6v02rSrKVy/LyjPbe6I4W/EBPGkGbgtnOsCsugIUvIqEOzYoouPrAnZARjExuA3IxE9ZAN2KVfcgRnMry8juYoG8QRDePStMVfA38VSMFxBf/Ikd8ZBVFFnXOElp8TWEvi/O5iGkH0j/ul0PDr5dbYIZ5+Fn4LZ0GN9U9nm7+M8Sqi7KYIPtcS/FwVquWzrKNZ8bVX0nKePqH6eWy/IoF9BQhZ7q3wx0JGPMnO0xw7iSJswlL9f8cgw0EZaXxvcrg0SdSPNUbHeS+ZffkDqZ49il2U7oCALETzmqi6bo5WexkVlReKHlRCcoxAUJCn9Pr5pmC5vMV22W4sxSG+tls3kVfaU6mVmLGhdjrwsCCFgSkztuzp7jD6s4AEnB8CieJefsx4Qw8MMxISNqDXD/isVV7ksYtmKwYJhOwwDn2qS+G9bs6QO5udGiE644KU5jqAaAHpOuANhWl0SYDc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
