appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Cuw9GZbCVKQBhuvrtnP5sygMhF6xYrX3zoH1QmxhqTDvy6QAtqVQc/rC5NvPTyH5Px9bsHl2/7ugLiDBH691FtwlSch2ZZCSqoDbfrMVEEGhEWzXimfYYJJuBy9ovutf39QdQXrenYdIj2ZHBJZVHqaS4hmvH2Gw01YooXRTNE6pGDyxKMYQkb+WxiTxlQ7fQ6KBPdrWg6l3r/5knFyxAzb3IvyKnsED7jR/CSkkpPSS3cUrXsAO+nzk1tjzkMjn2Jdp358EYBU5NbqyE20V4zAghAhimUAFuR5RVn87iYtPEulcuWBYKx8+Aw96O+gLZmrcvMVA0YIN5mgEjdP1TrC9CYtIBfQsd9vrq9tR7v4934DH1LK8MnqUyGIcyspKqd1+tuif4E7VxSst98ptMRhGXzrWJTwePkeC5fkYX+6lV6yxr0gC3T+XUC4oBVGBvWUUcBhRidSFteBy+Ws8Ydv7lIWj/5TrF1CcraunZb9s29LSBnvMsk71444oMREPiMACbZ+dCDl/uTsJwbNJgHCnKC9LtyVjJM8zZFFrePzDrQurUifxmhhIcWtWBNLEMPtOjUykugFqFdvbXBkvPoDjGeI3AtXR3VbcMJEroDfAH18V8C79gC7TnHAuUccdJkfyccrXQoO0+FvAhS/UXVZT6tELICAmvakDYCCW1T0=}
